// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Vec3f } from '../spec/vec3f.js';


export class BoundingLOD {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):BoundingLOD {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

center(obj?:Vec3f):Vec3f|null {
  return (obj || new Vec3f()).__init(this.bb_pos, this.bb!);
}

radius():number {
  return this.bb!.readFloat32(this.bb_pos + 12);
}

error():number {
  return this.bb!.readFloat32(this.bb_pos + 16);
}

static sizeOf():number {
  return 20;
}

static createBoundingLOD(builder:flatbuffers.Builder, center_x: number, center_y: number, center_z: number, radius: number, error: number):flatbuffers.Offset {
  builder.prep(4, 20);
  builder.writeFloat32(error);
  builder.writeFloat32(radius);
  builder.prep(4, 12);
  builder.writeFloat32(center_z);
  builder.writeFloat32(center_y);
  builder.writeFloat32(center_x);
  return builder.offset();
}

}
