// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { BoundingBox } from '../spec/bounding-box.js';
import { SparseDistanceFieldMip } from '../spec/sparse-distance-field-mip.js';


export class DistanceFieldVolumeData {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):DistanceFieldVolumeData {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsDistanceFieldVolumeData(bb:flatbuffers.ByteBuffer, obj?:DistanceFieldVolumeData):DistanceFieldVolumeData {
  return (obj || new DistanceFieldVolumeData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsDistanceFieldVolumeData(bb:flatbuffers.ByteBuffer, obj?:DistanceFieldVolumeData):DistanceFieldVolumeData {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new DistanceFieldVolumeData()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

localSpaceMeshBounds(obj?:BoundingBox):BoundingBox|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new BoundingBox()).__init(this.bb_pos + offset, this.bb!) : null;
}

alwaysLoadedMip(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

alwaysLoadedMipLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

alwaysLoadedMipArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

streamableMips(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

streamableMipsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

streamableMipsArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

mips(index: number, obj?:SparseDistanceFieldMip):SparseDistanceFieldMip|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new SparseDistanceFieldMip()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

mipsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startDistanceFieldVolumeData(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addLocalSpaceMeshBounds(builder:flatbuffers.Builder, localSpaceMeshBoundsOffset:flatbuffers.Offset) {
  builder.addFieldStruct(0, localSpaceMeshBoundsOffset, 0);
}

static addAlwaysLoadedMip(builder:flatbuffers.Builder, alwaysLoadedMipOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, alwaysLoadedMipOffset, 0);
}

static createAlwaysLoadedMipVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startAlwaysLoadedMipVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addStreamableMips(builder:flatbuffers.Builder, streamableMipsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, streamableMipsOffset, 0);
}

static createStreamableMipsVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startStreamableMipsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addMips(builder:flatbuffers.Builder, mipsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, mipsOffset, 0);
}

static createMipsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startMipsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endDistanceFieldVolumeData(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createDistanceFieldVolumeData(builder:flatbuffers.Builder, localSpaceMeshBoundsOffset:flatbuffers.Offset, alwaysLoadedMipOffset:flatbuffers.Offset, streamableMipsOffset:flatbuffers.Offset, mipsOffset:flatbuffers.Offset):flatbuffers.Offset {
  DistanceFieldVolumeData.startDistanceFieldVolumeData(builder);
  DistanceFieldVolumeData.addLocalSpaceMeshBounds(builder, localSpaceMeshBoundsOffset);
  DistanceFieldVolumeData.addAlwaysLoadedMip(builder, alwaysLoadedMipOffset);
  DistanceFieldVolumeData.addStreamableMips(builder, streamableMipsOffset);
  DistanceFieldVolumeData.addMips(builder, mipsOffset);
  return DistanceFieldVolumeData.endDistanceFieldVolumeData(builder);
}
}
