// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { BLEND_MODE } from '../spec/blend-mode.js';
import { MaterialBakedAsset } from '../spec/material-baked-asset.js';
import { MaterialPBRAsset } from '../spec/material-pbrasset.js';
import { MaterialPhongAsset } from '../spec/material-phong-asset.js';
import { RENDER_MODE } from '../spec/render-mode.js';
import { SHADING_MODE } from '../spec/shading-mode.js';


export class MaterialAsset {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MaterialAsset {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMaterialAsset(bb:flatbuffers.ByteBuffer, obj?:MaterialAsset):MaterialAsset {
  return (obj || new MaterialAsset()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMaterialAsset(bb:flatbuffers.ByteBuffer, obj?:MaterialAsset):MaterialAsset {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MaterialAsset()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

uuid():string|null
uuid(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
uuid(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

shadingMode():SHADING_MODE {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : SHADING_MODE.UNLIT;
}

twoSided():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

enableWireframe():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

blendFunc():BLEND_MODE {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : BLEND_MODE.DEFAULT;
}

opacity():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

renderMode():RENDER_MODE {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : RENDER_MODE.OPAQUE;
}

pbr(obj?:MaterialPBRAsset):MaterialPBRAsset|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? (obj || new MaterialPBRAsset()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

phong(obj?:MaterialPhongAsset):MaterialPhongAsset|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? (obj || new MaterialPhongAsset()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

baked(obj?:MaterialBakedAsset):MaterialBakedAsset|null {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? (obj || new MaterialBakedAsset()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startMaterialAsset(builder:flatbuffers.Builder) {
  builder.startObject(10);
}

static addUuid(builder:flatbuffers.Builder, uuidOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, uuidOffset, 0);
}

static addShadingMode(builder:flatbuffers.Builder, shadingMode:SHADING_MODE) {
  builder.addFieldInt32(1, shadingMode, SHADING_MODE.UNLIT);
}

static addTwoSided(builder:flatbuffers.Builder, twoSided:number) {
  builder.addFieldInt32(2, twoSided, 0);
}

static addEnableWireframe(builder:flatbuffers.Builder, enableWireframe:number) {
  builder.addFieldInt32(3, enableWireframe, 0);
}

static addBlendFunc(builder:flatbuffers.Builder, blendFunc:BLEND_MODE) {
  builder.addFieldInt32(4, blendFunc, BLEND_MODE.DEFAULT);
}

static addOpacity(builder:flatbuffers.Builder, opacity:number) {
  builder.addFieldFloat32(5, opacity, 0.0);
}

static addRenderMode(builder:flatbuffers.Builder, renderMode:RENDER_MODE) {
  builder.addFieldInt32(6, renderMode, RENDER_MODE.OPAQUE);
}

static addPbr(builder:flatbuffers.Builder, pbrOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, pbrOffset, 0);
}

static addPhong(builder:flatbuffers.Builder, phongOffset:flatbuffers.Offset) {
  builder.addFieldOffset(8, phongOffset, 0);
}

static addBaked(builder:flatbuffers.Builder, bakedOffset:flatbuffers.Offset) {
  builder.addFieldOffset(9, bakedOffset, 0);
}

static endMaterialAsset(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
