// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ScalerAsset } from '../spec/scaler-asset.js';


export class MaterialBakedAsset {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MaterialBakedAsset {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMaterialBakedAsset(bb:flatbuffers.ByteBuffer, obj?:MaterialBakedAsset):MaterialBakedAsset {
  return (obj || new MaterialBakedAsset()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMaterialBakedAsset(bb:flatbuffers.ByteBuffer, obj?:MaterialBakedAsset):MaterialBakedAsset {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MaterialBakedAsset()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

ambientOcclusion(obj?:ScalerAsset):ScalerAsset|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new ScalerAsset()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

lightMap(obj?:ScalerAsset):ScalerAsset|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new ScalerAsset()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startMaterialBakedAsset(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addAmbientOcclusion(builder:flatbuffers.Builder, ambientOcclusionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, ambientOcclusionOffset, 0);
}

static addLightMap(builder:flatbuffers.Builder, lightMapOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, lightMapOffset, 0);
}

static endMaterialBakedAsset(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
