// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ScalerAsset } from '../spec/scaler-asset.js';


export class MaterialPhongAsset {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MaterialPhongAsset {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMaterialPhongAsset(bb:flatbuffers.ByteBuffer, obj?:MaterialPhongAsset):MaterialPhongAsset {
  return (obj || new MaterialPhongAsset()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMaterialPhongAsset(bb:flatbuffers.ByteBuffer, obj?:MaterialPhongAsset):MaterialPhongAsset {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MaterialPhongAsset()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

diffuse(obj?:ScalerAsset):ScalerAsset|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new ScalerAsset()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

specular(obj?:ScalerAsset):ScalerAsset|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new ScalerAsset()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

shiness(obj?:ScalerAsset):ScalerAsset|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new ScalerAsset()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

ambient(obj?:ScalerAsset):ScalerAsset|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new ScalerAsset()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

emissive(obj?:ScalerAsset):ScalerAsset|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new ScalerAsset()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

reflectivity(obj?:ScalerAsset):ScalerAsset|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new ScalerAsset()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startMaterialPhongAsset(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addDiffuse(builder:flatbuffers.Builder, diffuseOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, diffuseOffset, 0);
}

static addSpecular(builder:flatbuffers.Builder, specularOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, specularOffset, 0);
}

static addShiness(builder:flatbuffers.Builder, shinessOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, shinessOffset, 0);
}

static addAmbient(builder:flatbuffers.Builder, ambientOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, ambientOffset, 0);
}

static addEmissive(builder:flatbuffers.Builder, emissiveOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, emissiveOffset, 0);
}

static addReflectivity(builder:flatbuffers.Builder, reflectivityOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, reflectivityOffset, 0);
}

static endMaterialPhongAsset(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
