// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ScalerAsset } from '../spec/scaler-asset.js';


export class MaterialPBRAsset {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):MaterialPBRAsset {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMaterialPBRAsset(bb:flatbuffers.ByteBuffer, obj?:MaterialPBRAsset):MaterialPBRAsset {
  return (obj || new MaterialPBRAsset()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMaterialPBRAsset(bb:flatbuffers.ByteBuffer, obj?:MaterialPBRAsset):MaterialPBRAsset {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new MaterialPBRAsset()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

baseColor(obj?:ScalerAsset):ScalerAsset|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new ScalerAsset()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

metallic(obj?:ScalerAsset):ScalerAsset|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new ScalerAsset()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

roughness(obj?:ScalerAsset):ScalerAsset|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new ScalerAsset()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

emissive(obj?:ScalerAsset):ScalerAsset|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new ScalerAsset()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

sheenColor(obj?:ScalerAsset):ScalerAsset|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new ScalerAsset()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

sheenRoughness(obj?:ScalerAsset):ScalerAsset|null {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new ScalerAsset()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

clearcoat(obj?:ScalerAsset):ScalerAsset|null {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? (obj || new ScalerAsset()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

clearcoatRoughness(obj?:ScalerAsset):ScalerAsset|null {
  const offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? (obj || new ScalerAsset()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

clearcoatNormal(obj?:ScalerAsset):ScalerAsset|null {
  const offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? (obj || new ScalerAsset()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

anisotropy(obj?:ScalerAsset):ScalerAsset|null {
  const offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? (obj || new ScalerAsset()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

transmission(obj?:ScalerAsset):ScalerAsset|null {
  const offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? (obj || new ScalerAsset()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

volumeThickness(obj?:ScalerAsset):ScalerAsset|null {
  const offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? (obj || new ScalerAsset()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startMaterialPBRAsset(builder:flatbuffers.Builder) {
  builder.startObject(12);
}

static addBaseColor(builder:flatbuffers.Builder, baseColorOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, baseColorOffset, 0);
}

static addMetallic(builder:flatbuffers.Builder, metallicOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, metallicOffset, 0);
}

static addRoughness(builder:flatbuffers.Builder, roughnessOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, roughnessOffset, 0);
}

static addEmissive(builder:flatbuffers.Builder, emissiveOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, emissiveOffset, 0);
}

static addSheenColor(builder:flatbuffers.Builder, sheenColorOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, sheenColorOffset, 0);
}

static addSheenRoughness(builder:flatbuffers.Builder, sheenRoughnessOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, sheenRoughnessOffset, 0);
}

static addClearcoat(builder:flatbuffers.Builder, clearcoatOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, clearcoatOffset, 0);
}

static addClearcoatRoughness(builder:flatbuffers.Builder, clearcoatRoughnessOffset:flatbuffers.Offset) {
  builder.addFieldOffset(7, clearcoatRoughnessOffset, 0);
}

static addClearcoatNormal(builder:flatbuffers.Builder, clearcoatNormalOffset:flatbuffers.Offset) {
  builder.addFieldOffset(8, clearcoatNormalOffset, 0);
}

static addAnisotropy(builder:flatbuffers.Builder, anisotropyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(9, anisotropyOffset, 0);
}

static addTransmission(builder:flatbuffers.Builder, transmissionOffset:flatbuffers.Offset) {
  builder.addFieldOffset(10, transmissionOffset, 0);
}

static addVolumeThickness(builder:flatbuffers.Builder, volumeThicknessOffset:flatbuffers.Offset) {
  builder.addFieldOffset(11, volumeThicknessOffset, 0);
}

static endMaterialPBRAsset(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
