// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { BoundingLOD } from '../spec/bounding-lod.js';


export class Meshlet {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Meshlet {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsMeshlet(bb:flatbuffers.ByteBuffer, obj?:Meshlet):Meshlet {
  return (obj || new Meshlet()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsMeshlet(bb:flatbuffers.ByteBuffer, obj?:Meshlet):Meshlet {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Meshlet()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

refined(obj?:BoundingLOD):BoundingLOD|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new BoundingLOD()).__init(this.bb_pos + offset, this.bb!) : null;
}

self(obj?:BoundingLOD):BoundingLOD|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new BoundingLOD()).__init(this.bb_pos + offset, this.bb!) : null;
}

simplified(obj?:BoundingLOD):BoundingLOD|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new BoundingLOD()).__init(this.bb_pos + offset, this.bb!) : null;
}

indices(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint32(this.bb!.__vector(this.bb_pos + offset) + index * 4) : 0;
}

indicesLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

indicesArray():Uint32Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? new Uint32Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startMeshlet(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addRefined(builder:flatbuffers.Builder, refinedOffset:flatbuffers.Offset) {
  builder.addFieldStruct(0, refinedOffset, 0);
}

static addSelf(builder:flatbuffers.Builder, selfOffset:flatbuffers.Offset) {
  builder.addFieldStruct(1, selfOffset, 0);
}

static addSimplified(builder:flatbuffers.Builder, simplifiedOffset:flatbuffers.Offset) {
  builder.addFieldStruct(2, simplifiedOffset, 0);
}

static addIndices(builder:flatbuffers.Builder, indicesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, indicesOffset, 0);
}

static createIndicesVector(builder:flatbuffers.Builder, data:number[]|Uint32Array):flatbuffers.Offset;
/**
 * @deprecated This Uint8Array overload will be removed in the future.
 */
static createIndicesVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset;
static createIndicesVector(builder:flatbuffers.Builder, data:number[]|Uint32Array|Uint8Array):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt32(data[i]!);
  }
  return builder.endVector();
}

static startIndicesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endMeshlet(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
