// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { TEXTURE_MAPPING } from '../spec/texture-mapping.js';
import { TEXTURE_MAP_MODE } from '../spec/texture-map-mode.js';
import { TEXTURE_OP } from '../spec/texture-op.js';


export class SamplerAsset {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SamplerAsset {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSamplerAsset(bb:flatbuffers.ByteBuffer, obj?:SamplerAsset):SamplerAsset {
  return (obj || new SamplerAsset()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSamplerAsset(bb:flatbuffers.ByteBuffer, obj?:SamplerAsset):SamplerAsset {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SamplerAsset()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

uuid():string|null
uuid(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
uuid(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

uvindex():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

blend():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

mapping():TEXTURE_MAPPING {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : TEXTURE_MAPPING.UV;
}

mapMode():TEXTURE_MAP_MODE {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : TEXTURE_MAP_MODE.WRAP;
}

op():TEXTURE_OP {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : TEXTURE_OP.MULTIPLY;
}

static startSamplerAsset(builder:flatbuffers.Builder) {
  builder.startObject(6);
}

static addUuid(builder:flatbuffers.Builder, uuidOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, uuidOffset, 0);
}

static addUvindex(builder:flatbuffers.Builder, uvindex:number) {
  builder.addFieldInt32(1, uvindex, 0);
}

static addBlend(builder:flatbuffers.Builder, blend:number) {
  builder.addFieldInt32(2, blend, 0);
}

static addMapping(builder:flatbuffers.Builder, mapping:TEXTURE_MAPPING) {
  builder.addFieldInt32(3, mapping, TEXTURE_MAPPING.UV);
}

static addMapMode(builder:flatbuffers.Builder, mapMode:TEXTURE_MAP_MODE) {
  builder.addFieldInt32(4, mapMode, TEXTURE_MAP_MODE.WRAP);
}

static addOp(builder:flatbuffers.Builder, op:TEXTURE_OP) {
  builder.addFieldInt32(5, op, TEXTURE_OP.MULTIPLY);
}

static endSamplerAsset(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSamplerAsset(builder:flatbuffers.Builder, uuidOffset:flatbuffers.Offset, uvindex:number, blend:number, mapping:TEXTURE_MAPPING, mapMode:TEXTURE_MAP_MODE, op:TEXTURE_OP):flatbuffers.Offset {
  SamplerAsset.startSamplerAsset(builder);
  SamplerAsset.addUuid(builder, uuidOffset);
  SamplerAsset.addUvindex(builder, uvindex);
  SamplerAsset.addBlend(builder, blend);
  SamplerAsset.addMapping(builder, mapping);
  SamplerAsset.addMapMode(builder, mapMode);
  SamplerAsset.addOp(builder, op);
  return SamplerAsset.endSamplerAsset(builder);
}
}
