// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Vec4f } from '../spec/vec4f.js';


export class ScalerAsset {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ScalerAsset {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsScalerAsset(bb:flatbuffers.ByteBuffer, obj?:ScalerAsset):ScalerAsset {
  return (obj || new ScalerAsset()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsScalerAsset(bb:flatbuffers.ByteBuffer, obj?:ScalerAsset):ScalerAsset {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ScalerAsset()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

scaler(obj?:Vec4f):Vec4f|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Vec4f()).__init(this.bb_pos + offset, this.bb!) : null;
}

textureUuid():string|null
textureUuid(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
textureUuid(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

samplerUuid():string|null
samplerUuid(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
samplerUuid(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startScalerAsset(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addScaler(builder:flatbuffers.Builder, scalerOffset:flatbuffers.Offset) {
  builder.addFieldStruct(0, scalerOffset, 0);
}

static addTextureUuid(builder:flatbuffers.Builder, textureUuidOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, textureUuidOffset, 0);
}

static addSamplerUuid(builder:flatbuffers.Builder, samplerUuidOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, samplerUuidOffset, 0);
}

static endScalerAsset(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createScalerAsset(builder:flatbuffers.Builder, scalerOffset:flatbuffers.Offset, textureUuidOffset:flatbuffers.Offset, samplerUuidOffset:flatbuffers.Offset):flatbuffers.Offset {
  ScalerAsset.startScalerAsset(builder);
  ScalerAsset.addScaler(builder, scalerOffset);
  ScalerAsset.addTextureUuid(builder, textureUuidOffset);
  ScalerAsset.addSamplerUuid(builder, samplerUuidOffset);
  return ScalerAsset.endScalerAsset(builder);
}
}
