// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Vec2f } from '../spec/vec2f.js';
import { Vec3f } from '../spec/vec3f.js';
import { Vec3i } from '../spec/vec3i.js';


export class SparseDistanceFieldMip {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SparseDistanceFieldMip {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSparseDistanceFieldMip(bb:flatbuffers.ByteBuffer, obj?:SparseDistanceFieldMip):SparseDistanceFieldMip {
  return (obj || new SparseDistanceFieldMip()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSparseDistanceFieldMip(bb:flatbuffers.ByteBuffer, obj?:SparseDistanceFieldMip):SparseDistanceFieldMip {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SparseDistanceFieldMip()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

indirectionDimensions(obj?:Vec3i):Vec3i|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Vec3i()).__init(this.bb_pos + offset, this.bb!) : null;
}

numDistanceFieldBricks():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

volumeToVirtualUvScale(obj?:Vec3f):Vec3f|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new Vec3f()).__init(this.bb_pos + offset, this.bb!) : null;
}

volumeToVirtualUvAdd(obj?:Vec3f):Vec3f|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new Vec3f()).__init(this.bb_pos + offset, this.bb!) : null;
}

distanceFieldToVolumeScaleBias(obj?:Vec2f):Vec2f|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new Vec2f()).__init(this.bb_pos + offset, this.bb!) : null;
}

bulkOffset():number {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

bulkSize():number {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startSparseDistanceFieldMip(builder:flatbuffers.Builder) {
  builder.startObject(7);
}

static addIndirectionDimensions(builder:flatbuffers.Builder, indirectionDimensionsOffset:flatbuffers.Offset) {
  builder.addFieldStruct(0, indirectionDimensionsOffset, 0);
}

static addNumDistanceFieldBricks(builder:flatbuffers.Builder, numDistanceFieldBricks:number) {
  builder.addFieldInt32(1, numDistanceFieldBricks, 0);
}

static addVolumeToVirtualUvScale(builder:flatbuffers.Builder, volumeToVirtualUvScaleOffset:flatbuffers.Offset) {
  builder.addFieldStruct(2, volumeToVirtualUvScaleOffset, 0);
}

static addVolumeToVirtualUvAdd(builder:flatbuffers.Builder, volumeToVirtualUvAddOffset:flatbuffers.Offset) {
  builder.addFieldStruct(3, volumeToVirtualUvAddOffset, 0);
}

static addDistanceFieldToVolumeScaleBias(builder:flatbuffers.Builder, distanceFieldToVolumeScaleBiasOffset:flatbuffers.Offset) {
  builder.addFieldStruct(4, distanceFieldToVolumeScaleBiasOffset, 0);
}

static addBulkOffset(builder:flatbuffers.Builder, bulkOffset:number) {
  builder.addFieldInt32(5, bulkOffset, 0);
}

static addBulkSize(builder:flatbuffers.Builder, bulkSize:number) {
  builder.addFieldInt32(6, bulkSize, 0);
}

static endSparseDistanceFieldMip(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
