// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum TEXTURE_OP {
  MULTIPLY = 0,
  ADD = 1,
  SUBTRACT = 2,
  DIVIDE = 3,
  SMOOTH_ADD = 4,
  SIGNED_ADD = 5
}
