// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum TEXTURE_MAPPING {
  UV = 0,
  SHPERE = 1,
  CYLINDER = 2,
  BOX = 3,
  PLANE = 4,
  OTHER = 5
}
