// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum TEXTURE_MAP_MODE {
  WRAP = 0,
  CLAMP = 1,
  MIRROR = 2,
  DECAL = 3
}
